### ISSUE TITLE
Resolve image error in name screen

### ISSUE THREAD

**Issue by simplybest12** [DSC-JSS-NOIDA/Doingly#3]
Without selecting image a user are not being able to go in home sceen , try to resolve this error in flutter

**Comment by ayato91** [comment]
@simplybest12 Hey Deepanshu, Check and accept my PR. Thank you

**Comment by yyuvraj54** [comment]
assign this issue to me and please merge it

**Comment by ayato91** [comment]
@yyuvraj54  I already made a pull request for this issue lol
